
spring:
  main:
    allow-bean-definition-overriding: true
    cloud-platform: kubernetes
  application:
    name: showcase-admin-tool
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          url-expression: "'http://'+serviceId"
    kubernetes:
      reload:
        enabled: true
        mode: polling
        period: 5000
      discovery:
        filter: "metadata.labels['spring-boot']"
  boot:
    admin:
      monitor:
        status-lifetime: 5000ms
        status-interval: 5000ms
        default-timeout: 5000ms
  profiles:
    active:
      - secure
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
    restart:
      enabled: true
      health:
    info:
      enabled: true
debug: true
---

spring:
  config:
    activate:
      on-profile: secure
  security:
    user:
      name: "user"
      password: "password"

---

spring:
  config:
    activate:
      on-profile: insecure
